# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:
          ls
          git remote add linux4sam git://github.com/linux4sam/linux-at91.git
          git remote update linux4sam
          git branch -r
          git checkout origin/linux-5.4-at91 -b linux-5.4-at91
          export CROSS_COMPILE=arm-linux-gnueabi-
          make at91_dt_defconfig
          make ARCH=arm
          echo Add other actions to build,
          echo test, and deploy your project.
